"ui.background" = "black"
"ui.text" = "white"
"ui.selection" = { fg = "black", bg = "blue" }
"ui.cursor.match" = "blue"
"ui.cursor" = { fg = "black", bg = "blue" }
"ui.linenr" = "white"
"ui.linenr.selected" = { fg = "blue", modifiers = ["bold"] }
"ui.statusline" = "white"
"ui.statusline.inactive" = "gray"
"ui.statusline.insert" = { fg = "black", bg = "white" }
"ui.statusline.select" = { fg = "black", bg = "blue" }
"ui.window" = "white"
"ui.highlight" = "blue"
"ui.text.focus" = "blue"
"ui.virtual.ruler" = { bg = "gray" }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "red", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue", style = "curl" } }

"warning" = "red"
"error" = "red"
"info" = "blue"
"hint" = "blue"

"keyword" = { fg = "blue", modifiers = ["bold"] }
"comment" = { fg = "gray" }
"string" = { fg = "white" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }

[palette]
white = "#ffffff"
black = "#000000"
blue = "#818eae"
gray = "#3a3b3b"
green = "#90b38a"
red = "#c08484"
