"ui.background" = "black"
"ui.text" = "white"
"ui.selection" = { fg = "black", bg = "blue" }
"ui.cursor.match" = "blue"
"ui.cursor" = { fg = "black", bg = "blue" }
"ui.linenr" = "white"
"ui.linenr.selected" = { fg = "blue", modifiers = ["bold"] }
"ui.statusline" = "white"
"ui.statusline.inactive" = "gray"
"ui.statusline.insert" = { fg = "black", bg = "blue" }
"ui.highlight" = "blue"
"ui.window" = "white"

"error" = "red"

"keyword" = { fg = "blue", modifiers = ["bold"] }
"comment" = { fg = "gray" }
"string" = { fg = "white" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }

[palette]
white = "#ffffff"
black = "#000000"
blue = "#818eae"
gray = "#585959"
green = "#90b38a"
red = "#c08484"
