theme = "tokyonight_storm"

[editor]
cursorline = true
color-modes = true
bufferline = "always"
mouse = false

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
"C-q" = ":buffer-close"
"A-j" = [ # Move current line down
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "goto_line_start"
]
"A-k" = [ # Move current line up
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "goto_line_start"
]
"esc" = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
