theme = "rose_pine_moon"

[editor]
cursorline = true
color-modes = true
mouse = false
idle-timeout = 0 # Instant autocomplete
scrolloff = 10
line-number = "relative"
bufferline = "always"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"C-q" = ":buffer-close"
"A-j" = [ # Move current line down by 1
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "goto_line_start"
]
"A-k" = [ # Move current line up by 1
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "goto_line_start"
]
"esc" = [
  "collapse_selection",
  "keep_primary_selection"
]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
