theme = "rose_pine_moon"

[editor]
cursorline = true
color-modes = true
mouse = false
idle-timeout = 0 # Instant autocomplete
line-number = "relative"
bufferline = "always"
completion-trigger-len = 1

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
skip-levels = 1
 
[editor.statusline]
right = ["diagnostics", "position-percentage", "file-type"]

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
"C-q" = ":buffer-close"
"A-j" = [ # Move current line down by 1
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "goto_line_start"
]
"A-k" = [ # Move current line up by 1
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "goto_line_start"
]
"esc" = [
  "collapse_selection",
  "keep_primary_selection"
]
"ret" = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
