theme = "dracula"

[editor]
cursorline = true
color-modes = true
mouse = false
idle-timeout = 5
line-number = "relative"
bufferline = "always"
completion-trigger-len = 1 # Enable autocompletion after first character is typed.

[editor.gutters]
# Git diff before line numbers
layout = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
skip-levels = 1
 
[editor.statusline]
right = ["diagnostics", "position", "spacer", "position-percentage", "file-type"]

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[keys.normal]
# Move current line down (j) by 1
"A-j" = [ 
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "goto_line_start"
]
# Move current line up (k) by 1
"A-k" = [ 
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "goto_line_start"
]
"esc" = [
  "collapse_selection",
  "keep_primary_selection"
]
# Enter works in normal mode.
"ret" = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
q = ":buffer-close"

# TODO: Append with "mip" and ":reflow" to reflow on paragraph.
W = [
  "select_all",
  "split_selection_on_newline",
  "trim_selections",
  "select_textobject_inner",
]
