[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
# I got this from: https://github.com/helix-editor/helix/issues/3231#issuecomment-1876996743
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = "" # I might need to check if this is correct

[[language]]
name = "html"

[[language]]
name = "css"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
rulers = [120]
language-servers = ["typescript-language-server", "eslint"]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
rulers = [120]

[[language]]
name = "bash"

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "marksman", "ltex-ls" ]

# This is a temporary workaround for adding custom words to the dictionary.
# Please check the thread (https://github.com/helix-editor/helix/issues/7636) once in a while
# to validate of there is a better implementation available.
[language-server.ltex-ls.config]
ltex.dictionary = { "en-US" = [
  "builtin",
  "NetworkManager",
  "worktree",
  "worktrees",
  "Worktree",
  "Worktrees",
  "dotfile",
  "dotfiles",
  "Dotfile",
  "Dotfiles",
  "eduroam",
  "Eduroam",
  "iwd",
  "Iwd",
  "feat",
  "Feat",
  "gitconfig",
  "tmux",
  "Tmux"
], "nl-NL" = [
  "builtin"
]}
