[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
# I got this from: https://github.com/helix-editor/helix/issues/3231#issuecomment-1876996743
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = "" # I might need to check if this is correct

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "ltex-ls"]
rulers = [120]
auto-format = false

[[language]]
name = "css"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
rulers = [120]
language-servers = ["typescript-language-server", "eslint"]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
rulers = [120]

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/home/th7mo/.nvm/versions/node/v20.11.0/lib"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "bash"

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
rulers = [80]
language-servers = [ "marksman", "ltex-ls" ]

[[language]]
name = "text"
scope = "source.text"
file-types = ["txt"]
rulers = [60]
text-width = 60

# This is a temporary workaround for adding custom words to the dictionary.
# Please check the thread (https://github.com/helix-editor/helix/issues/7636) once in a while
# to validate of there is a better implementation available.
[language-server.ltex-ls.config]
ltex.dictionary = { "en-US" = [
  "builtin",
  "NetworkManager",
  "worktree",
  "worktrees",
  "Worktree",
  "Worktrees",
  "dotfile",
  "dotfiles",
  "Dotfile",
  "Dotfiles",
  "eduroam",
  "Eduroam",
  "iwd",
  "Iwd",
  "feat",
  "Feat",
  "gitconfig",
  "tmux",
  "Tmux",
  "wikilink",
  "Wikilink",
  "wikilinks",
  "Wikilinks",
  "href",
  "hx",
  "Kakoune",
  "toml",
  "TODO",
  "li",
  "ol",
  "ul",
  "refact",
  "astro",
  "Astro",
  "Zsh",
  "Anypoint",
  "Mulesoft",
  "OpenAPI",
  "Rekordbox",
  "rekordbox",
  "Hemiron",
  "OpenTelemetry",
  "Sentry"
], "nl-NL" = [
  "builtin",
  "Anypoint",
  "Mulesoft",
  "OpenAPI"
]}
