[[language]]
name = "html"

[[language]]
name = "css"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
rulers = [120]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
rulers = [120]

[[language]]
name = "bash"

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]

# This is a temporary workaround for adding custom words to the dictionary.
# Please check the thread (https://github.com/helix-editor/helix/issues/7636) once in a while
# to validate of there is a better implementation available.
[language-server.ltex-ls.config]
ltex.dictionary = { "en-US" = [
  "builtin",
  "NetworkManager",
  "worktree",
  "worktrees",
  "Worktree",
  "Worktrees",
  "dotfile",
  "dotfiles",
  "Dotfile",
  "Dotfiles",
  "eduroam",
  "Eduroam",
  "iwd",
  "Iwd",
  "feat",
  "Feat"
], "nl-NL" = [
  "builtin"
]}
